### PR TITLE
saving globe effect changes

### PR DESCRIPTION
**Pull request by alok-kumar-ovyo**
This is demo PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/4)

### CODE REVIEW

**Review by iamaloke — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alok-kumar-ovyo)

**Review by iamaloke — CHANGES_REQUESTED** [review]
This demo suggestion

> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/4#-:-O8I5HyFEvwzim4E6ZZi:bs93sec)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alok-kumar-ovyo)

**Review by alok-kumar-ovyo — COMMENTED** [review]
changes done, please review

> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/4#-:-O8I6FxX-NtdskUWHxD3:bwnypw6)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @iamaloke)

**Review by iamaloke — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/4)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alok-kumar-ovyo)

**Review by alok-kumar-ovyo — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alok-kumar-ovyo)

**Review by alok-kumar-ovyo — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/4#-:-O8I8tqm4kePRUE3Cxmt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alok-kumar-ovyo)

**Pull request merged**
