### PR TITLE
updated gitignore file

### PR DESCRIPTION
**Pull request by alok-kumar-ovyo**
updated gitignore file

- - -
This change is [Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/2)

### CODE REVIEW

**Review by alok-kumar-ovyo — COMMENTED** [review]
check 1

> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/2#-:-O86sMEJ-TEimT9EE_Rp:b-n7tdos)* status: 0 of 2 files reviewed, all discussions resolved

**Review by alok-kumar-ovyo — COMMENTED** [review]
check 2

> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/2#-:-O86t7jsBeWBJbcBtL7F:b-n7tdor)* status: 0 of 2 files reviewed, all discussions resolved

**Review by iamaloke — CHANGES_REQUESTED** [review]
check 3 - iamaloke

> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/2#-:-O86xB5OAny0MHf8aUpR:b-gz2ksa)* status: 0 of 2 files reviewed, all discussions resolved

**Review by alok-kumar-ovyo — COMMENTED** [review]
changes done

> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/2#-:-O86yJjZCT5pURKOSSey:b-ttakl8)* status: 0 of 2 files reviewed, all discussions resolved

**Review by iamaloke — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/2)* status: 0 of 2 files reviewed, all discussions resolved

**Review by alok-kumar-ovyo — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alok-kumar-ovyo/reviewabledemo/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iamaloke)

**Pull request closed without merging**
